INSERT INTO student (skill_level,person_id)
VALUES
  ('intermediate',16),
  ('intermediate',17),
  ('beginner',18),
  ('intermediate',19),
  ('intermediate',20),
  ('beginner',21),
  ('beginner',22),
  ('intermediate',23),
  ('beginner',24),
  ('beginner',25);
INSERT INTO student (skill_level,person_id)
VALUES
  ('beginner',26),
  ('advanced',27),
  ('beginner',28),
  ('beginner',29),
  ('intermediate',30),
  ('beginner',31),
  ('beginner',32),
  ('beginner',33),
  ('advanced',34),
  ('advanced',35);
INSERT INTO student (skill_level,person_id)
VALUES
  ('advanced',36),
  ('intermediate',37),
  ('beginner',38),
  ('advanced',39),
  ('advanced',40),
  ('advanced',41),
  ('advanced',42),
  ('intermediate',43),
  ('advanced',44),
  ('advanced',45);
INSERT INTO student (skill_level,person_id)
VALUES
  ('beginner',46),
  ('beginner',47),
  ('advanced',48),
  ('beginner',49),
  ('intermediate',50),
  ('advanced',51),
  ('intermediate',52),
  ('intermediate',53),
  ('advanced',54),
  ('advanced',55);
INSERT INTO student (skill_level,person_id)
VALUES
  ('advanced',56),
  ('intermediate',57),
  ('advanced',58),
  ('intermediate',59),
  ('intermediate',60),
  ('beginner',61),
  ('intermediate',62),
  ('intermediate',63),
  ('advanced',64),
  ('intermediate',65);
